//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by resource.rc
//
#define IDD_SETCOLOR                    101
#define IDC_SCROLLBAR1                  1000
#define IDC_SCROLLBAR2                  1001
#define IDC_SCROLLBAR3                  1002
#define IDC_VALUE_RED                   1003
#define IDC_VALUE_GREEN                 1004
#define IDC_VALUE_BLUE                  1005
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1006
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
