//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by resource.rc
//
#define IDD_INPUT                       101
#define IDC_Y_MAX                       1000
#define IDC_Y_MIN                       1001
#define IDC_X_MAX                       1002
#define IDC_X_MIN                       1003
#define IDC_LINES                       1004
#define IDC_RESET                       1006

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1008
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
